// Priority: -100
if (global.datagenDialog) {
  runNpcDatagen("shepherd", {
    name: "Maria",
    intro: [
      "Hello, my name is Maria. I'll be here to get you started ranching on your farm.",
      "Raising animals take lots of time, energy and care.",
      "In the end seeing the look on a happy animal's face is well worth it!",
      "If you need any supplies just let me know."
    ],
    chatter: {
      friendship0: [
        ["Hello there, need anything?"],
        ["I'm not used to being out in the wild like this.", "It's exciting to see all the wildlife!"],
        ["How's your farm going?", "Have you gotten started with some animals yet?"],
        ["It's eerie here at night, I'm not used to this must open air."],
        ["Do you need something?"],
        ["Need to pick something up?"],
        ["The valley is full of wild slimes...", "They always catch me off guard and pop out of nowhere."],
        ["Have you seen Ace around?"],
        ["What can I do for you today?"],
        ["Hello @i."],
        ["I could use a warm cup of coffee right now..."],
        ["I'm often skeptical of new farmers I see try to take on ranching.", "Some of them have a rotten soul unfit to care for them."],
        ["I'm not sure about Leon... ", "I've never met someone so distant."],
        ["Always curious about where these new farmers will end up.", "Not everyone's cut out for the hard life of labor."],
        ["Everyone here is so friendly, it kinda weirds me out.", "No not like that! I'm just not used to it!"],
      ],
      friendship1: [
        ["I saw some wild sheep roaming around the other day.", "They look like they could use a warm barn..."],
        ["No need to stop around so often", "I'm more than capable of handling myself out here."],
        [
          "When you choose a name for your animals, it creates a special bond between you and them.",
          "Make sure you name them something that fits their personality!",
        ],
        ["How are things on your farm?"],
        ["Everything is so calm and simple around here...", "I'm excited to see how things change over time."],
        ["Ace gave me some Salmonberries to munch on today!", "No wonder I see squirrels digging around for them all the time."],
        ["Feel free to stop by if you have any questions about animals."],
        ["Do you want something?"],
        ["How are you today?"],
        ["Hey @i, what can I do for you?"],
        ["Everybody lies, but animals will always tell you the truth.", "Except racoons, those always try and trick you!"],
        ["How is Aiden so cheerful standing in that heat all day?"],
        ["Why did Leon even move out here?", "I've never met someone that hates nature more."],
        ["I miss the stray cats of the city I grew up in...", "Stray sheep are a different kind of nice though!"],
      ],
      friendship2: [
        ["All these new people in town...", "Moving to a new town sure is rough."],
        [
          "I've seen some nasty farmers out there that treat their animals cruelly.",
          "Giant holding pens stuffed to the brim... Makes me sick...",
          "I'm glad you're not like that!"
        ],
        ["Running low on animal feed?", "Or are you here to adopt!"],
        ["I've been loving seeing all the wild animals run around freely lately."],
        ["There's something about the air here that's so freeing."],
        ["I hope you're feeding your animals every day.", "You'd be grumpy to if you had to skip a meal!"],
        ["You should see if you can make a Catching Net!", "There's so many wonderful butterflies around the valley."],
        ["I don't have the heart to garden, all my plants always end up over-watered..."],
        ["I love the feeling of weaving on a Canvas Loom.", "There's nothing quite like it."],
        ["Leon was so sour today when I went to get groceries.", "People can be so mean when they're tired."],
        ["People's hearts are often unveiled with their treatment of animals."],
        ["Some people can be so disappointing in life.", "Ahh but nobody here is like that! Probably..."],
        [
          "Grains like Wheat and Corn can be made into Animal Feed.",
          "I'm sure your animals will appreciate fresher food than what I've got!"
        ],
      ],
      friendship3: [
        ["Need more feed?"],
        ["Have you considered ranching pigs?", "Truffles are great for making donuts!"],
        ["Have you talked to Aiden recently?", "I really need that order of pails..."],
        ["Animals have no concept of the evils we are capable of.", "It's our job to make sure they never find out."],
        ["You can tell a lot about a person by the way they approach a scared animal."],
        ["I was reading about Minisheep today in the farmer's almanac.", "...So fluffy..."],
        ["Caroline is a sucker for goat cheese.", "Don't mention I said that! I want to know more secrets..."],
        ["Leon has sewing supplies stocked at the market.", "Let me know if you need lessons!"],
        ["Caroline has some expensive taste.", "Most people don't have an eye for proper merino wool."],
        ["Your hands are so calloused!", "Let me take a look later, I have a serum made from sheeps milk that will help."],
        ["Do you ever think about what our animals dream about?"],
        ["Someone like you could really use some pets.", "I bet it gets lonely over where you are."],
      ],
      friendship4: [
        ["Originally I thought Leon disliked me in particular.", "Turns out they're just like that."],
        ["There's nothing as sweet as the love of an animal."],
        ["Hey @i, what are you up to today?"],
        ["How's your ranch going today?"],
        ["You sure like spending time with me.", "Or maybe you have some sort of ulterior motive..."],
        ["You really have no rhythm when talking to me.", "I never know when to expect you."],
        ["I wonder if building out this town effects your ego in any way.", "People here will always keep you humble I bet!"],
        ["Caroline can be so mean!", "It's one of the more frustrating things of living here."],
        ["There's so much to industrial farming that I dislike.", "I understand the realities of keeping society going...", "Just don't mistreat animals, I'll know."],
        ["There's a myth around farmers that having too many animals will incur the wrath of Selene.", "She's so real..."],
        ["Have you heard about goobers?", "I've heard they're native place called the Skull Cavern, wherever that is."],
        ["Ace was telling me about mossberries the other day.", "I bet they'd make a great jam."],
        ["People around here will just come up to me and tell me their secrets.", "I guess I look trusting to them?"],
        ["I've been knitting some sweaters for the harsh winters around here.", "Not that you need one for all that running around you do every day!"],
      ],
      friendship5: [
        [
          "Leon let me sample some of your animal products the other day.",
          "Everything was so fresh and full of flavor!",
        ],
        ["Leon sure likes talking about Caroline.", "I wonder what that's about..."],
        ["People sometimes think that I don't like people just because I have a love of animals.", "I'm glad you're not one of them"],
        ["Ahh! I was looking for you @i."],
        ["What's on your schedule @i?"],
        ["What can I do for you?"],
        ["Some people think they can win me over with gifts and small talk.", "That's not a real connection, and you know that."],
        ["You've really got an eye for getting to know people.", "You're very easy to talk to so it makes sense."],
        ["The way a shima enaga tilts its tiny head is a wonder of the world.", "Truly a snow fairy!"],
        ["What a calm day today..."],
        ["What would you like?"],
        ["People think pigs are monsters for what people force them to eat.", "Animals teach us so much about humanity."],
        ["Ace wants to see you about something.", "I wonder what you to talk about when nobody's looking."],
        ["I knew I'd see you today, I stocked some extra feed ahead of time!"],
        ["Caroline isn't one of those people that's a sweetheart once you get to know them.", "Usually I'm right about these things."],
        ["Your ambitions are so frightening to me...", "I hope pulling up the roots of this valley is worth whatever you're trying to accomplish."],
        [
          "There's something so nice about the way an animal looks at you with loving eyes.",
          "Nothing quite like it.",
        ],
      ],
    },
    giftResponse: {
      loved: [
        "This makes me feel very at home.",
        "You're so sweet to me, this is one of my favorites!",
        "This is one of my favorites!",
        "What a sweet gift, thank you @i.",
        "This makes me feel very welcome here.",
        "How'd you know I love these?",
        "Wow! This is so luxurious.",
        "I really love this!",
        "This is an amazing gift."
      ],
      liked: [
        "Thank you, I really appreciate it.",
        "I know the perfect spot for this!",
        "I was looking for this at the market the other day! How'd you know?",
        "So thoughtful! Thank you.",
        "Is this from your farm? This is lovely.",
        "This is a very considerate gift.",
        "Very lovely, I appreciate this.",
        "You're a sweetheart!",
        "It's so nice to have people like you here.",
        "Thank you very much!"
      ],
      neutral: [
        "Thank you!",
        "That's sweet of you.",
        "I think one of my friends would like this!",
        "You're very kind.",
        "Is this from your farm? I've never seen one quite like this.",
        "Thanks!",
        "Ahh thanks!",
        "I'll take it!",
      ],
      disliked: [
        "Oh! I wasn't expecting something like this.",
        "You must know animals way better than people...",
        "Sometimes it's better to not give gifts.",
        "Oh!",
        "Oh...",
        "Ah... Okay... Cool...",
        "Did you mean to give this to someone else?",
        "We don't really have to give gifts to each other...",
      ],
      hated: [
        "Why...",
        "Why?",
        "...",
        "You can just ask me to leave directly.",
        "No thank you.",
        "This doesn't make me feel good...",
        "I'm not sure I want this...",
        "Can you leave me alone please.",
        "I don't like these kinds of jokes.",
        "Sorry but I really don't want this...",
        "This might be the worst thing I've ever been given..."
      ],
    },
    unique: [
      {
        name: "five_gift",
        text: [
          "Oh hello @i, I actually have a small favor for you!",
          "Ace found these penguins out on an expedition to a frozen wasteland and told me to take care of them.",
          "I don't mean to just shift the responsibility to you, but I really trust you to treat them with the care they deserve.",
          "Unfortunately I don't have the means to build up a proper ice habitat, they wouldn't be happy with me.",
          "If you're struggling with their mood, just pick up a mood scanner at my shop! It should be pretty cheap for you."
        ]
      },
    ]
  });
}