#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 22 18:03:25 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1 + Clrwl_1.0.0.zip
enableShaders=false
